### ISSUE TITLE
Prepare keycloak to consume cryptographic keys provided by a keystore

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#24]
OIDC4VC aith SD=-JWT will require ECDSA keys. In order to generate them we can use openssl.
```zsh
# New Shell
# Generate a ECDSA keypair for keycloak
# openssl ecparam -genkey -name prime256v1 -out private_key.pem -algorithm ecdsa
# These three lines will generate: private_key.pem, public_key.pem, certificate.crt
openssl ecparam -genkey -name prime256v1 -out private_key.pem
openssl ec -in private_key.pem -pubout -out public_key.pem
openssl req -x509 -new -nodes -key private_key.pem -sha256 -days 365 -out certificate.crt -config cert-config.txt

```
Here is the file references in the script:
[cert-config.txt](https://github.com/adorsys/keycloak-ssi-deployment/files/14787630/cert-config.txt)

But we still have to import this result into a keystore. In short, we have to import all keycloak key into a key store and not have them generated by the servers.

We need to find out:
- how to move all keycloak keys to a keystore.
- how to configure keycloak to consume those keys.

**Comment by bengo237** [comment]
To move all the Keycloak keys to a keystore, we can follow these steps:

1. **Generate the Keystore**: First, create a keystore file where you will import the keys. You can use the Java `keytool` command for this purpose.

```bash
keytool -genkeypair -alias keycloak -keyalg EC -keysize 256 -validity 365 -keystore keycloak.keystore
```

2. **Import Keys to Keystore**: Then, you'll need to import the keys generated by OpenSSL into this keystore.

```bash
openssl pkcs8 -topk8 -nocrypt -in private_key.pem -inform PEM -out private_key.pk8 -outform DER
keytool -importcert -file certificate.crt -alias keycloak_cert -keystore keycloak.keystore
keytool -import -file public_key.pem -alias keycloak_public_key -keystore keycloak.keystore
keytool -import -file private_key.pk8 -alias keycloak_private_key -keystore keycloak.keystore
```

3. **Verify**: You can verify that the keys have been successfully imported into the keystore using the following command:

```bash
keytool -list -v -keystore keycloak.keystore
```

This will list all the entries in the keystore, including the keys you just imported.

Now, you have all the Keycloak keys moved to the `keycloak.keystore` file. Make sure to secure this keystore file properly as it contains sensitive information.

**Comment by bengo237** [comment]
To move the generated keys (private_key.pem, public_key.pem, certificate.crt) into a keystore and configure Keycloak to consume them, you can follow these steps:

1. **Move Keys to Keystore:**
   You'll need to create a PKCS#12 keystore and import the keys into it. You can use the `openssl` command for this purpose.

   ```bash
   openssl pkcs12 -export -in certificate.crt -inkey private_key.pem -out keycloak_keystore.p12 -name keycloak_key
   ```
   This command will create a keystore named `keycloak_keystore.p12` and import the certificate and private key into it.


2. **List Keystore Contents**: You can use the `keytool` command to list the contents of the keystore and verify that the certificate and private key were imported correctly.

    ```bash
    keytool -list -v -keystore keycloak_keystore.p12 -storetype PKCS12 -storepass your_keystore_password
    ```

    Replace `keycloak_keystore.p12` with the path to your keystore file and `your_keystore_password` with the password you used when creating the keystore. This command will display the contents of the keystore, including the certificate and private key entries.

**Comment by bengo237** [comment]
have issue to set keycloak consume the generated key

**Comment by bengo237** [comment]
![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/85441363/9e1de0ad-7e6c-47d9-afa0-c86fd442f8b3)



 Keycloak is expecting an RSA private key, but it's encountering an EC (Elliptic Curve) private key instead.

**Comment by bengo237** [comment]
Starting the automation of the process

**Comment by ArmandMeppa** [comment]
## Update of 24/04/2024
- Configured the pipeline to automatically build and deploy the custom kcoid4vci to AWS ECR and ECS

**Comment by bengo237** [comment]
https://github.com/adorsys/keycloak-ssi-deployment/pull/30#pullrequestreview-2027838176

**Comment by nitch2019** [comment]
EC2 Instance for Test shows some errors.
Meeting planned with Yannick /Stephane to check

**Comment by bengo237** [comment]
https://keycloak.solutions.adorsys.com/

**Comment by bengo237** [comment]
https://keycloak.solutions.adorsys.com/realms/master/.well-known/openid-credential-issuer

**Comment by francis-pouatcha** [comment]
Here is a link on how to configure realm keys under keycloak: https://www.keycloak.org/docs/latest/server_admin/index.html#realm_keys

Here is a link on how to load a keypair from a java keystore: https://www.keycloak.org/docs/latest/server_admin/index.html#realm_keys

**Comment by nitch2019** [comment]
PR to @bengo237 and @ArmandMeppa

**Comment by francis-pouatcha** [comment]
https://github.com/adorsys/keycloak-ssi-deployment/pull/33

**Comment by bengo237** [comment]
Reviewed #33
