### ISSUE TITLE
Use keycloak config cli to build our kc environment on aws

### ISSUE THREAD

**Issue by ArmandMeppa** [adorsys/keycloak-ssi-deployment#35]
Use Terraform to configure and deploy our kc as IaC, with best practices and security measures.

Please start with:
https://www.keycloak.org/guides

**Comment by francis-pouatcha** [comment]
I do not understand what i have to review here. How do we deploy keycloak?

I provided these scripts so we can use as example to define some automated CD of keycloak.

What i need is the use of a keycloak deployment approach. Here is a list of deployment approaches for Keycloak CI/CD:

1. **Adorsys Keycloak Config CLI:** A command-line tool to manage Keycloak configurations and automate deployment tasks.
2. **Keycloak Terraform Provider:**  A Terraform provider for managing Keycloak resources as part of your infrastructure-as-code approach.
3. **Keycloak Operator:** A Kubernetes operator that simplifies the deployment and management of Keycloak on Kubernetes clusters.
4. **Docker Compose:** A tool for defining and running multi-container Docker applications, including Keycloak.
5. **Ansible Playbooks:** Ansible scripts that automate the installation, configuration, and deployment of Keycloak.
6. **Shell Scripts:** Custom scripts that automate Keycloak deployment steps using command-line tools.
7. **Helm Charts:** Packages for deploying applications on Kubernetes, including pre-configured Keycloak deployments.
8. **Custom Operators:** Kubernetes operators specifically designed for managing Keycloak deployments, offering more control and customization than the official operator.
9. **Dedicated CI/CD Tools:** CI/CD platforms like Jenkins, GitLab CI/CD, or GitHub Actions, which may have plugins or integrations specifically for Keycloak.

This list covers the most common and effective approaches for deploying Keycloak in a CI/CD pipeline. The choice of an approach will depend on specific requirements, infrastructure, and familiarity with different tools.

Question: which approach are we using to deploy keycloak on the AWS-EC2 environment?

**Comment by francis-pouatcha** [comment]
Simple and nice Keycloak tutorial:
- https://www.altkomsoftware.com/blog/keycloak-security-in-microservices/

Just some mor eexamples of keycloak on AWS
- https://aws-samples.github.io/keycloak-on-aws/en/implementation-guide/deployment/
- https://aws-samples.github.io/keycloak-on-aws/en/implementation-guide/tutorials/api-gateway/

On MUltitenancy
- https://www.hcltech.com/blogs/keycloak-multitenancy

**Comment by bengo237** [comment]
Keycloak deployment Concept 

![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/85441363/2d61177e-e412-455d-8b95-8f8315ac5aba)

**Comment by bengo237** [comment]
[Retrieve Secrets Manager secrets through Amazon ECS environment variables](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html)

**Comment by nitch2019** [comment]
Working of Onboarding the students to take over the task

**Comment by Marcjazz** [comment]
@ArmandMeppa and @bengo237 are currently on boarding the students and they will follow with this ticket from next week

**Comment by hugoib** [comment]
Import of different configuration is the remaining part.

**Comment by forkimenjeckayang** [comment]
Having this error when trying to export  our KC configurations to live instance
![Image](https://github.com/user-attachments/assets/bc5b705c-ce69-471a-83ae-5950c31747c0)

**Comment by forkimenjeckayang** [comment]
The error above  was due to the path of the keystore file.Since our KC instance is running in a container the file system structure changed.
Here is the correct path 
```bash
/opt/keycloak/target/kc_keystore.pkcs12
```
Running locally the realm export works well but using the container running keycloak we have another issue with the sd-jwt-signing-service
![Image](https://github.com/user-attachments/assets/733204b0-9145-4cc3-ba9a-ee6af0eb9589)

**Comment by forkimenjeckayang** [comment]
- We have a working keycloak image to start our keycloak and a script which uses the keycloak config CLI to import our configurations
- The problems mentioned above were solved by dropping all the tables in the persistent online DB, updating our ECS service and re-running the script that configures our  KC instance.

![Image](https://github.com/user-attachments/assets/1a63d957-af07-4c8d-9434-54fa1b147610)
