### ISSUE TITLE
Configure keycloak not to release authChecker.js

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#41]
Is there a way to disable by configuration the feature leading to loading the authChecker.js script? I've diagnosed that it is the one emitting the request that breaks the flow. From searching the web, the script synchronizes cookies across different tabs... I guess we can proceed without for now. The current workaround I use is to tell the browser not to load or run the script. For reference, this is a link to it: https://keycloak.solutions.adorsys.com/resources/90qy4/login/keycloak/js/authChecker.js

2nd Where verifier will be loaded: Block JS
    Chrome settings
    Privacy and security
        Site settings
            Javascript
                Add to not allowed to use JavaScript: [*.]keycloak.solutions.adorsys.com t

**Comment by francis-pouatcha** [comment]
Instructions on running an example:

1) Preparation:
    1.1)
    On phone: 
        1) Go to https://cors-anywhere.herokuapp.com/corsdemo  
        2) press 'Request temporary access to the demo server'
    

    1.2) 
    Where verifier will be loaded: 
    Chrome settings
    Privacy and security
        Site settings
            Javascript
                Add to: 'not allowed to use JavaScript': 
                    [*.]keycloak.solutions.adorsys.com

2) Demo

Wallet (phone):
    https://adorsys.github.io/eudiw-app/


Issuer (browser):
    https://kci-portal.solutions.adorsys.com/

    username:
        francis
    password:
        francis

If it fails, just go again to the FE address

Verifier (browser):
    https://kcv-portal.solutions.adorsys.com/

**Comment by nitch2019** [comment]
will be handle by https://github.com/adorsys/be-kc-client-oid4vc/issues/9
