### ISSUE TITLE
Keycloak: Obtaining the credential, requires credential_identifier, troubleshoot and fix

### ISSUE THREAD

**Issue by hugoib** [adorsys/keycloak-ssi-deployment#43]
On the last step of credential issuance, keycloak receives the value credential_identifier:

![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/4196617/5e2854a4-4522-4ff4-8eb9-a94efe3b4c23)

This doesn't happen on the wallet side:

It was added for the demo, troubleshoot and fix:

![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/4196617/b2f005be-a778-4d54-a65f-c935111cec6a)

**Comment by Marcjazz** [comment]
The spec says it should be provided if it was return by the token endpoint:


![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/61763373/faa0f337-babb-485f-8a4b-763b0fc5bf76)

**Comment by francis-pouatcha** [comment]
Ok. I misunderstood this. Means we have to use the vct field instead right?

**Comment by IngridPuppet** [comment]
Yes, that would have been my conclusion too. 

If the server expects a `credential_identifier`, then it must specifies `credential_identifiers` as part of the token response under the `authorization_details` field, which in turn seems only relevant in the Authorized Code flow (not pre-authorized).


![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/30264663/0354e0d4-b84b-430d-b20e-62e8ea6b3e30)


Also, `credential_identifier` must definitely not be required at the same time with `format`.

**Comment by IngridPuppet** [comment]
Will potentially be addressed by:
- https://github.com/keycloak/keycloak/issues/30907
