### ISSUE TITLE
Keycloak: Credential time field is named 'nbf' but on the wallet is 'iat'

### ISSUE THREAD

**Issue by hugoib** [adorsys/keycloak-ssi-deployment#44]
For the demo, the following change was made:

![Image](https://github.com/adorsys/keycloak-ssi-deployment/assets/4196617/77aca5d1-0321-4dd5-b59e-cd777fc2448b)

**Comment by Marcjazz** [comment]
@francis-pouatcha I have gone through the keycloack oid4vc issuance implementation, I noticed that we've default the value of the `nbf` claim to `iat` but we've not added the iat claim/value set in our rootNode.

I will like to cease this opportunity to contribute to keycloack. 

https://github.com/adorsys/keycloak-oid4vc/blob/e3f8e70f61cf7f41d6b9c79bfac8af46e781df1b/services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SdJwtSigningService.java#L126

**Comment by francis-pouatcha** [comment]
Field is not mandatory, was removed with:
- https://github.com/keycloak/keycloak/pull/30692

**Comment by IngridPuppet** [comment]
We cannot merge it yet. We'll send another PR to Keycloak.

**Comment by francis-pouatcha** [comment]
Issue: https://github.com/keycloak/keycloak/issues/31581
PR: https://github.com/keycloak/keycloak/pull/31582
