### ISSUE TITLE
Keycloack is requesting for `code` instead of `pre-authorized_code` on the issuance flow

### ISSUE THREAD

**Issue by Marcjazz** [adorsys/keycloak-ssi-deployment#45]
Keycloack is requesting for `code` instead of `pre-authorized_code` on the issuance flow when the grant type is `urn:ietf:params:oauth:grant-type:pre-authorized_code`

**Comment by Marcjazz** [comment]
@francis-pouatcha Please assign yourself the ticket as I don't have the required permissions to do so

**Comment by hugoib** [comment]
There is already a ticket for this. Thanks Marco! Closing it:

https://github.com/adorsys/keycloak-ssi-deployment/issues/42/
