### ISSUE TITLE
Setup a demo environment and restore a working branch of KC for demo purpose

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#47]
We need a dedicated demo environment
We shall have it working:
- either with the branch working so far, or
- with the current head.

**Comment by nitch2019** [comment]
waiting for sync in https://github.com/adorsys/keycloak-ssi-deployment/issues/55

**Comment by Awambeng** [comment]
Demo env set on aws. It can be accessed via https://keycloak-demo.solutions.adorsys.com

**Comment by nitch2019** [comment]
Pls check if the configuration have benn transferred in the Demo env. and check if the env. is working well.
@hugoib

**Comment by hugoib** [comment]
The demo environment is up and running, it is missing one part:

https://github.com/adorsys/keycloak-ssi-deployment/issues/57

I created that ticket and I am closing this one.
