### ISSUE TITLE
Keycloak: Return 401 not 500 when bearer token has expired (on credential offer endpoint)

### ISSUE THREAD

**Issue by IngridPuppet** [adorsys/keycloak-ssi-deployment#54]
There is a potential issue (of low severity) to address in Keycloak. 

Context: The credential offer endpoint authenticates calls via a bearer token.

```bash
curl --location 'https://keycloak.solutions.adorsys.com/realms/master/protocol/oid4vc/credential-offer/vA6D3rO2WqzRAOkAYpSNhspLaZJmOjOG' \
--header 'Accept: application/json' \
--header "Authorization: Bearer $TOKEN"
```

However, when the token has expired, this call results in a 500 Internal Server error. I believe it should be something like 401 Unauthorized.

**Comment by nitch2019** [comment]
blocked and waiting for https://github.com/keycloak/keycloak/pull/30692

**Comment by francis-pouatcha** [comment]
See comment in pull request and in discord.

**Comment by IngridPuppet** [comment]
Will be addressed by:
- https://github.com/keycloak/keycloak/pull/31587

**Comment by nitch2019** [comment]
add integration tests

**Comment by nitch2019** [comment]
back to kc pr
