### ISSUE TITLE
Address potential OID4VC issues in keycloak

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#73]
Issues are in the following presentation from Takashi. From there we will create a subticket for each issue we want to address
 
[PotentialIssuesOnOID4VCI.pdf](https://github.com/user-attachments/files/16510273/PotentialIssuesOnOID4VCI.pdf)

As for [1], it seems that Keycloak can only support SD-JWT effectively.

As for [2], the issue has already resolved by [https://github.com/keycloak/keycloak/pull/31763](https://github.com/keycloak/keycloak/pull/31763)

This link also addresses open items from closed issues: https://github.com/keycloak/keycloak/issues/created_by/francis-pouatcha

**Comment by francis-pouatcha** [comment]
[PotentialIssuesOnOID4VCI.pdf](https://github.com/user-attachments/files/16510273/PotentialIssuesOnOID4VCI.pdf)

**Comment by nitch2019** [comment]
Pls check and create relevant tickets here

**Comment by nitch2019** [comment]
the PR should be addressed on Keycloack

**Comment by nitch2019** [comment]
This ticket serves as reference.
Tickets have been already discussed and created on Kc
