### ISSUE TITLE
Redeploy keycloak-demo with a working version

### ISSUE THREAD

**Issue by IngridPuppet** [adorsys/keycloak-ssi-deployment#74]
### Description
Credentials cannot be retrieving from https://keycloak-demo.solutions.adorsys.com.

### How to reproduce?
- Set KEYCLOAK_EXTERNAL_ADDR=https://keycloak-demo.solutions.adorsys.com in `.env`
- Run `3.retrieve_IdentityCredential.sh`.

```
Credential: {"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."} 
```
### Addendum
Note that KEYCLOAK_EXTERNAL_ADDR=https://keycloak.solutions.adorsys.com works as expected.

**Comment by forkimenjeckayang** [comment]
Hello Sir @IngridPuppet 
The Demo keycloak has been redeployed with requested changes
Please check again if you still have issues

**Comment by IngridPuppet** [comment]
It is working. Thank you.
