### ISSUE TITLE
Keycloak 25.05 Compatibility and Dedicated Realm Support

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#87]
**Description:**

This ticket aims to enhance the `keycloak-ssi-deployment` project to achieve the following goals:

* **Keycloak 25.05 Compatibility:** Check the project seamlessly integrates with Keycloak version 25.05.
* **Dedicated Realm Support:** Implement the ability to deploy a dedicated realm for SSI (Self-Sovereign Identity) operations within Keycloak. This isolation will provide better security and management control for SSI-related configurations and data.
* **Hacking Test OIDC4VCI:**  This updated deployment will facilitate focused testing of the OIDC4VCI protocol, specifically focusing on identifying potential vulnerabilities and security weaknesses.

**Implementation Approach:**

1. **Keycloak 25.05 Upgrade:** Update the keycloak version and configurations to align with Keycloak 25.05.
2. **Dedicated Realm:**
   *  Utilize `keycloak-config-cli` to export the necessary realm configuration. 
   *  Modify `keycloak-ssi-deployment` to create and manage a dedicated realm for SSI during deployment. 
3. **Secret Management:**
   *  Integrate `keycloak-config-cli`'s secret management features into the deployment process. 
   *  Securely store and manage sensitive configuration data, such as database credentials and client secrets.

**Testing:**

* **Functional Testing:** Perform comprehensive testing to validate the compatibility with Keycloak 25.05 and the correct operation of the dedicated realm.
* **OIDC4VCI Hacking Test:** Execute targeted tests against the OIDC4VCI protocol implementation to identify potential security flaws and vulnerabilities.

**Additional Considerations:**

*  **Documentation:** Update the project documentation to reflect the changes and provide clear instructions on how to deploy and configure the dedicated realm for SSI.
* **Backward Compatibility:** Assess the impact of the changes on existing deployments and ensure backward compatibility whenever possible. If breaking changes are unavoidable, provide clear migration instructions.

**Expected Outcome:**

A robust and secure deployment of `keycloak-ssi-deployment` that is:

*  Compatible with Keycloak 25.05.
*  Capable of creating and managing a dedicated realm for SSI.
*  Equipped with secret management capabilities.
*  Ready for use in hacking tests to evaluate the security of the OIDC4VCI protocol.

**Comment by hugoib** [comment]
This might help: ![Image](https://github.com/user-attachments/assets/5e034730-fa9b-4d3f-9021-6985e2b0412c)

**Comment by hugoib** [comment]
Ticket can be closed, the changes will stay on this branch: https://github.com/adorsys/keycloak-ssi-deployment/tree/feat/upgrade-to-keycloak-25.0.5
